### ISSUE TITLE
non-GAE

### ISSUE THREAD

**Issue by duke-arioch** [pniederw/spockwebconsole#3]
would a non-GAE version be much work? trying to decide if i should go from scratch or dig into the code here? this looks really nice so far. sorry its as an issue - i didnt see much other way for communicating?

**Comment by pniederw** [comment]
Spock Web Console is a fork of Groovy Web Console, which is a Gaelyk based web app. I can't really tell how much work a non-GAE version would be. Best place to discuss Spock-related issues is: http://forum.spockframework.org
